# Generated by Django 4.1.7 on 2023-03-22 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0025_product_category'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrowseSession',
            new_name='BrowserHistory',
        ),
    ]
