# Generated by Django 4.1.7 on 2023-03-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsehistory',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
