# Generated by Django 4.1.7 on 2023-04-20 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frequently_bought_with',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
