# Generated by Django 4.1.7 on 2023-04-20 19:34

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_frequently_bought_with_productgrouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(default=''),
            preserve_default=False,
        ),
    ]
