# Generated by Django 4.1.7 on 2023-04-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview_comment_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
