# Generated by Django 4.1.7 on 2023-04-15 18:57

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('insurance_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='customer.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeItemPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('insurance_purchased', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='FullOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('order_id', models.CharField(default=orders.models.generate_order_id, max_length=20, unique=True)),
                ('is_over_21', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('drivers_license_id', models.CharField(blank=True, max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insurance_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('are_we_transporting_initial', models.BooleanField(default=True)),
                ('are_we_transporting_return', models.BooleanField(default=True)),
                ('payment_method', models.CharField(max_length=30)),
                ('is_paid', models.BooleanField(default=False)),
                ('rented_dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('delivered', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
                ('initial_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_initial_location', to='orders.address')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('auto_apply', models.BooleanField(default=False)),
                ('flat_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percentage_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('stacks_with_other_promos', models.BooleanField(default=False)),
                ('validation_function_name', models.CharField(max_length=100)),
                ('free_items', models.ManyToManyField(related_name='promotions', through='orders.FreeItemPromo', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insurance_purchased', models.BooleanField(default=False)),
                ('insurance_base_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insurance_daily_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_blueelf_transport_initial', models.BooleanField(default=True)),
                ('is_blueelf_transport_return', models.BooleanField(default=True)),
                ('rented_dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('delivered', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('full_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_full_order', to='orders.fullorder')),
                ('initial_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_initial_location', to='orders.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_product', to='products.product')),
                ('return_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_return_location', to='orders.address')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_stock', to='products.stock')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemFavorited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_items', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fullorder',
            name='promos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_promo', to='orders.promo'),
        ),
        migrations.AddField(
            model_name='fullorder',
            name='return_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_return_location', to='orders.address'),
        ),
        migrations.AddField(
            model_name='fullorder',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freeitempromo',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.promo'),
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('insurance_purchased', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
