# Generated by Django 4.1.7 on 2023-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_fullorder_email_remove_fullorder_is_over_21_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullorder',
            name='rented_dates',
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='promos',
            field=models.ManyToManyField(related_name='order_promo', to='orders.promo'),
        ),
    ]
