# Generated by Django 4.1.7 on 2023-05-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_fullorder_rented_dates_alter_fullorder_promos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullorder',
            name='initial_location',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='return_location',
        ),
    ]
