# Generated by Django 4.1.7 on 2023-05-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_fullorder_initial_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='initial_location',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='rented_dates',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='return_location',
        ),
    ]
