# Generated by Django 4.1.7 on 2023-04-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefernce_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
