# Generated by Django 4.1.7 on 2023-04-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_prefernce_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
