# Generated by Django 4.1.7 on 2023-03-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_category'),
        ('orders', '0002_rename_items_cartitems_item_remove_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='stock',
            field=models.ManyToManyField(null=True, to='products.stock'),
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='item',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
