# Generated by Django 4.1.7 on 2023-05-02 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_remove_itemorder_stock_alter_fullorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='is_over_21',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='promos',
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fullorder',
            name='promos',
            field=models.ManyToManyField(null=True, related_name='order_promo', to='orders.promo'),
        ),
    ]
