# Generated by Django 4.1.7 on 2023-03-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cart_customer_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='promos',
        ),
    ]
