# Generated by Django 4.1.7 on 2023-03-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_cartitems_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='stock',
        ),
    ]
