# Generated by Django 4.1.7 on 2023-03-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_cartitems_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='base_cost',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='daily_cost',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='insurance_base_cost',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='insurance_daily_cost',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
