# Generated by Django 4.1.7 on 2023-03-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_category'),
        ('orders', '0009_remove_cartitems_base_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfavorited',
            name='items',
        ),
        migrations.AddField(
            model_name='itemfavorited',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
