# Generated by Django 4.1.7 on 2023-03-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_itemfavorited_items_itemfavorited_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemfavorited',
            old_name='items',
            new_name='item',
        ),
    ]
