# Generated by Django 4.1.7 on 2023-04-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_category'),
        ('orders', '0013_fullorder_customer_promo_auto_apply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='flat_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='promo',
            name='free_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='percentage_discont',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
