# Generated by Django 4.1.7 on 2023-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_promo_flat_discount_alter_promo_free_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='stacks_with_other_promos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='validation_function_name',
            field=models.CharField(max_length=100),
        ),
    ]
