# Generated by Django 4.1.7 on 2023-04-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_browsehistory_customer'),
        ('orders', '0015_promo_stacks_with_other_promos_alter_promo_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='percentage_discont',
            new_name='percentage_discount',
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='customer.customer'),
        ),
    ]
