# Generated by Django 4.1.7 on 2023-04-05 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_category'),
        ('orders', '0016_rename_percentage_discont_promo_percentage_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promos',
        ),
        migrations.AlterField(
            model_name='promo',
            name='free_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
