# Generated by Django 4.1.7 on 2023-04-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_category'),
        ('orders', '0017_remove_cart_promos_alter_promo_free_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='free_item',
        ),
        migrations.CreateModel(
            name='FreeItemPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.promo')),
            ],
        ),
        migrations.AddField(
            model_name='promo',
            name='free_items',
            field=models.ManyToManyField(related_name='promotions', through='orders.FreeItemPromo', to='products.product'),
        ),
    ]
