# Generated by Django 4.1.7 on 2023-04-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_rename_product_freeitempromo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeitempromo',
            name='insurance_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
