# Generated by Django 4.1.7 on 2023-04-05 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_freeitempromo_insurance_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeitempromo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
