# Generated by Django 4.1.7 on 2023-03-10 19:50

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('average_rating', models.FloatField()),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insurance_base_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insurance_daily_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('main_img_location', models.CharField(max_length=255)),
                ('my_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_brand', to='products.brand')),
                ('frequently_bought_with', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sku', models.CharField(editable=False, max_length=20, unique=True)),
                ('purchase_date', models.DateField()),
                ('last_rented_date', models.DateField()),
                ('current_location', models.CharField(max_length=30)),
                ('rented_dates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateRangeField(), blank=True, null=True, size=None)),
                ('condition', models.CharField(choices=[('D', 'Damaged'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('N', 'New')], max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('prodcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('verified_purchaser', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('recommended', models.BooleanField(default=True)),
                ('header', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('reported', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_desc', models.TextField(validators=[products.models.ProductMInfo.validate_max_desc])),
                ('bullets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None)),
                ('prod_desc', models.TextField()),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('add_info_msrp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('add_info_manu', models.CharField(max_length=20)),
                ('ranking', models.IntegerField()),
                ('rank_link', models.CharField(max_length=60)),
                ('specs', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
