# Generated by Django 4.1.7 on 2023-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='full_name',
            field=models.CharField(default='yeti', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
