# Generated by Django 4.1.7 on 2023-03-10 21:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_full_name_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_path',
            field=models.CharField(default='jacob', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='my_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
