# Generated by Django 4.1.7 on 2023-03-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
