# Generated by Django 4.1.7 on 2023-04-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview_initial_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='comment_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='header',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
