# Generated by Django 4.1.7 on 2023-03-11 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_my_list_product_img_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productminfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
