# Generated by Django 4.1.7 on 2023-03-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stock_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='prodcut',
            new_name='product',
        ),
    ]
