# Generated by Django 4.1.7 on 2023-03-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_n_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productminfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.CharField(editable=False, max_length=120, unique=True),
        ),
    ]
