# Generated by Django 4.1.7 on 2023-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productminfo_product_alter_stock_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_rented_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
