# Generated by Django 4.1.7 on 2023-03-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_stock_last_rented_date_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='condition',
            field=models.CharField(choices=[('D', 'Damaged'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('N', 'New')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_location',
            field=models.CharField(default='Myrtle Beach, NC', max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
