# Generated by Django 4.1.7 on 2023-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_stock_condition_alter_stock_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productminfo',
            name='rank_link',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productminfo',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
