# Generated by Django 4.1.7 on 2023-03-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productminfo_rank_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_list',
        ),
        migrations.AddField(
            model_name='product',
            name='img_folder_path',
            field=models.CharField(default='lol', max_length=255),
            preserve_default=False,
        ),
    ]
