# Generated by Django 4.1.7 on 2023-03-13 15:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_folder_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_img_location',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.get_upload_path_prod),
        ),
    ]
