# Generated by Django 4.1.7 on 2023-03-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_category_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
