# Generated by Django 4.1.7 on 2023-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fe_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
