# Generated by Django 4.1.7 on 2023-04-14 18:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_category_fe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.get_upload_path_cat),
        ),
        migrations.CreateModel(
            name='FilterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('filter_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.filteroption')),
            ],
        ),
        migrations.AddField(
            model_name='filteroption',
            name='categories',
            field=models.ManyToManyField(to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_tags',
            field=models.ManyToManyField(blank=True, to='products.filtertag'),
        ),
    ]
