# Generated by Django 4.1.7 on 2023-04-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_filteroption_remove_product_tags_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filteroption',
            old_name='name',
            new_name='display_name',
        ),
    ]
