# Generated by Django 4.1.7 on 2023-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_name_filteroption_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteroption',
            name='internal_name',
            field=models.CharField(default='Test', max_length=60),
            preserve_default=False,
        ),
    ]
