# Generated by Django 4.1.7 on 2023-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_filteroption_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
    ]
